GeorgeCimpoeru/PoC

src/ecu_simulation/BatteryModule/Makefile
src/ecu_simulation/BatteryModule/include/BatteryModule.h
src/ecu_simulation/BatteryModule/include/HandleFrames.h
src/ecu_simulation/BatteryModule/src/BatteryModule.cpp
src/ecu_simulation/BatteryModule/src/HandleFrames.cpp
src/mcu/Makefile
src/mcu/include/HandleFrames.h
src/mcu/include/MCUModule.h
src/mcu/include/ReceiveFrames.h
src/mcu/src/HandleFrames.cpp
src/mcu/src/MCUModule.cpp
src/mcu/src/ReceiveFrames.cpp
src/mcu/src/main.cpp
src/mcu/test/HandleFrames_test.cpp
src/mcu/test/ReceiveFramesTest.cpp
src/uds/read_data_by_identifier/include/ReadDataByIdentifier.h
src/uds/read_data_by_identifier/src/ReadDataByIdentifier.cpp
src/utils/include/GenerateFrames.h
src/utils/src/GenerateFrames.cpp

- Added the service and used it in handleFrames
- Updated makefiles to compile Ecu files on MCU side and viceversa
- Added a default constructor on generateFrames because I forgot to add it in the previous PR
- Created a namespace on MCU side to avoid duplicate files on compile(two receiveFrames and two handleFrames)
- Made the module objects as externs to be able to access its data inside service.
- parseBatteryInfo now adds linux data into ecuData map according to DIDs document available on gspace.
Tested and works on both ECU and MCU side.
I will add more DIDs in the map when we decide which DIDs are needed.

ReadDataByIdentifier service

---

.github/workflows/style-checker.yml

The .github/workflows directory in your repository is searched for workflow files at the associated commit SHA or Git ref. The workflow files must be present in that commit SHA or Git ref to be considered.
For example, if the event occurred on a particular repository branch, then the workflow files must be present in the repository on that branch.
Thus I want to try to put this new script on DEV_BE

Create style-checker on a new branch

---

src/uds/authentication/include/SecurityAccess.h
src/uds/authentication/src/SecurityAccess.cpp

Improvements:
1)Added NRC exceededNumberOfAttempts and requiredTimeDelayNotExpired (implemented the cases when those could rise)
2)Added delaytimer in Negative response for requiredTimeDelayNotExpired(in milliseconds, bigendian format---example 5 miliseconds will be 00 00 00 05, we always have 4 bytes and we complete with 0x00 the padding before if necessary)
3)Solved bugs (one when timer was uint8 because i worked in seconds previously and i forgot to change, and another when i need to reset nr of attempts because delay timer expired, endTime must be reseted to a more larger time then now, condition when endTime expires is when now becomes greater than endTime)
4)Comments, documentation
5)Removed InterfaceLog(from previous commit), added more logs, method to convert the remaining time …

Feature/uds security access Improve 2 + bugs Solved

---

src/rest_api/actions/generate_frames.py
src/rest_api/requirements.txt
src/rest_api/utils/scripts/battery_read_info.sh
src/rest_api/utils/scripts/battery_read_info2.sh
src/rest_api/utils/scripts/engine_read_info.sh
src/rest_api/utils/scripts/req_ids.sh

din libraria threading, functia Lock() previne accesarea simultana a can bus-ului de catre mai multe threaduri

threading lock for can bus

---

src/ecu_simulation/BatteryModule/Makefile
src/mcu/Makefile
src/uds/authentication/include/SecurityAccess.h
src/uds/authentication/src/SecurityAccess.cpp
src/uds/authentication/utest/SecurityAccessTest.cpp
src/uds/ecu_reset/include/EcuReset.h
src/uds/ecu_reset/src/EcuReset.cpp
src/uds/read_data_by_identifier/include/ReadDataByIdentifier.h
src/uds/read_data_by_identifier/src/ReadDataByIdentifier.cpp
src/uds/read_data_by_identifier/utest/ReadDataByIdentifierTest.cpp
src/uds/routine_control/include/RoutineControl.h
src/uds/routine_control/src/RoutineControl.cpp
src/uds/write_data_by_identifier/include/WriteDataByIdentifier.h
src/uds/write_data_by_identifier/src/WriteDataByIdentifier.cpp
src/utils/include/NegativeResponse.h
src/utils/src/NegativeResponse.cpp

-Integrated SecurityAccess into: ECU Reset, readDatabyIdentifier, writeDataByIdentifier, routineControl
-Solved some bugs related to makefile rules(testerpresent and negative class)
-Discoverd bugs on rdbi and wdbi(on rdbi i fixed)
-Integrated Negative Response class into all of them
-Added the 2 main negative response cases according to general flow for negative response which need to be done before security check where they are not present
-Refactor Negative Response Class so that everyone can use the codes(they are public static, can be used without object class)
**Things to be done in the future: implement IPC logic such as ecu can access services when server is unlocked(MCU and ECU are 2 different processes), i tried shared memory but this will work only when the 2 processes run on …

Integrate SecurityService into UDS services that need it

---

src/ecu_simulation/BatteryModule/src/HandleFrames.cpp
src/mcu/src/HandleFrames.cpp
src/uds/tester_present/include/TesterPresent.h
src/uds/tester_present/src/TesterPresent.cpp

added a DiagnosticSessionControl object in TesterPresent class and pass it by refference in TesterPresent constructor;
switch to default session when S3 timer expires using diagnostic session control service.

TesterPresent integration with DiagnosticSessionControl

---

src/ecu_simulation/BatteryModule/include/BatteryModule.h
src/ecu_simulation/BatteryModule/include/ReceiveFrames.h
src/ecu_simulation/BatteryModule/src/BatteryModule.cpp
src/ecu_simulation/BatteryModule/src/ReceiveFrames.cpp
src/mcu/include/MCUModule.h
src/mcu/include/ReceiveFrames.h
src/mcu/src/HandleFrames.cpp
src/mcu/src/MCUModule.cpp
src/mcu/src/ReceiveFrames.cpp
src/uds/access_timing_parameters/include/AccessTimingParameter.h
src/uds/access_timing_parameters/src/AccessTimingParameter.cpp
src/uds/authentication/src/SecurityAccess.cpp
src/uds/clear_dtc/src/ClearDtc.cpp
src/uds/diagnostic_session_control/include/DiagnosticSessionControl.h
src/uds/diagnostic_session_control/src/DiagnosticSessionControl.cpp
src/uds/ecu_reset/src/EcuReset.cpp
src/uds/read_data_by_identifier/src/ReadDataByIdentifier.cpp
src/uds/read_dtc_information/src/ReadDtcInformation.cpp
src/uds/routine_control/src/RoutineControl.cpp
src/uds/tester_present/src/TesterPresent.cpp
src/uds/write_data_by_identifier/src/WriteDataByIdentifier.cpp
src/utils/include/NegativeResponse.h
src/utils/src/NegativeResponse.cpp

I integrated the DiagnosticSessionControl and AccessTimingParameter services into the MCU and Battery modules. Added functionality to time each frame's processing. If processing time exceeds ATP thresholds, an NRC is thrown; otherwise, the response is sent.

DSC&ATP services integration

---

src/ecu_simulation/BatteryModule/include/ReceiveFrames.h
src/ecu_simulation/BatteryModule/src/ReceiveFrames.cpp
src/mcu/include/ReceiveFrames.h
src/mcu/src/ReceiveFrames.cpp
src/uds/access_timing_parameters/src/AccessTimingParameter.cpp
src/uds/clear_dtc/src/ClearDtc.cpp
src/uds/diagnostic_session_control/src/DiagnosticSessionControl.cpp
src/uds/ecu_reset/src/EcuReset.cpp
src/uds/read_data_by_identifier/src/ReadDataByIdentifier.cpp
src/uds/read_dtc_information/src/ReadDtcInformation.cpp
src/uds/routine_control/src/RoutineControl.cpp
src/uds/tester_present/src/TesterPresent.cpp
src/uds/write_data_by_identifier/src/WriteDataByIdentifier.cpp

- I made it so that when a service exceeds the processing limit from ATP, it sends a Response-Pending NRC to let the client know the request is still being processed. Once the service finishes processing, it sends the response.
- Also, I added logic for services to consider either the p2_max_time or p2_start_max_time timer, depending on how long each service should take at most.

Updates to AccessTimingParameter integration logic

---

src/autoscripts/ecu_reset_hard.sh
src/ecu_simulation/BatteryModule/Makefile
src/mcu/Makefile
src/uds/ecu_reset/src/EcuReset.cpp

- The hard reset will function like a power-reset (All data will be reset to default, for example, if we perform a write, ECU hard reset, and then a read, the previously written value will be lost. I made a script which kills ECU main’s process and MCU main and then relaunch it(I renamed them in makefile to avoid bugs from having the same name, vscode for example has a process named main too).
- I integrated and also added NRC
- Solved the issue with sending response(on the old version, the response wasn't send and captured by MCU/ECU)

ECU reset Hard for ECU only works

---

src/ecu_simulation/BatteryModule/include/BatteryModule.h
src/ecu_simulation/BatteryModule/src/BatteryModule.cpp
src/mcu/include/MCUModule.h
src/mcu/src/MCUModule.cpp
src/ota/request_transfer_exit/src/RequestTransferExit.cpp
src/uds/access_timing_parameters/src/AccessTimingParameter.cpp
src/uds/clear_dtc/src/ClearDtc.cpp
src/uds/diagnostic_session_control/src/DiagnosticSessionControl.cpp
src/uds/ecu_reset/src/EcuReset.cpp
src/uds/read_data_by_identifier/include/ReadDataByIdentifier.h
src/uds/read_data_by_identifier/src/ReadDataByIdentifier.cpp
src/uds/read_dtc_information/src/ReadDtcInformation.cpp
src/uds/routine_control/src/RoutineControl.cpp
src/uds/tester_present/src/TesterPresent.cpp
src/uds/write_data_by_identifier/src/WriteDataByIdentifier.cpp
src/utils/src/NegativeResponse.cpp

Modify the WriteDataByIdentifier, ReadDataByIdentifier and RequestStatusExit services to write and read data from a file instead of a vector as it is currently implemented.

Add files to keep the mcu and battery data

---

src/ecu_simulation/BatteryModule/Makefile
src/mcu/Makefile

Removed duplicated lines
Checked all jobs
Reworked clean method to not output error if coverage folder doesn't exist

fix makefile ota

---

src/ecu_simulation/BatteryModule/Makefile
src/mcu/Makefile

Removed duplicated lines
Checked all jobs
Reworked clean method to not output error if coverage folder doesn't exist

corrected makefiles

---

src/ecu_simulation/BatteryModule/Makefile
src/ecu_simulation/BatteryModule/include/BatteryModule.h
src/ecu_simulation/BatteryModule/src/BatteryModule.cpp
src/mcu/Makefile
src/mcu/src/ReceiveFrames.cpp
src/uds/diagnostic_session_control/src/DiagnosticSessionControl.cpp
src/utils/include/ReceiveFrames.h
src/utils/src/ReceiveFrames.cpp

I modified the ReceiveFrames class in the BatteryModule to make it usable by all ECUs

Create one ReceiveFrames class for all ECUs

---

src/autoscripts/start_simulation.sh
src/uds/read_dtc_information/src/ReadDtcInformation.cpp

Removed flow control frame check and reversed receiver_id.
Also updated start_simulation.sh script because binary files' name changed.

small fix for readDtc

---

src/ecu_simulation/BatteryModule/src/main.cpp
src/mcu/include/ReceiveFrames.h
src/mcu/src/ReceiveFrames.cpp
src/uds/authentication/include/SecurityAccess.h
src/uds/authentication/src/SecurityAccess.cpp
src/uds/read_data_by_identifier/src/ReadDataByIdentifier.cpp
src/uds/write_data_by_identifier/src/WriteDataByIdentifier.cpp
src/utils/src/HandleFrames.cpp
src/utils/src/ReceiveFrames.cpp

Updated IPC:
- Now it is up to date with handle and receive frames reworks(because handleFrames now use one socket only)
- Logic for notify moved from service into receiveframes
- Logic for notify if the security timer expires (0xCE if security is unlocked, 0xCF if security is locked)
- Linked readDatabyIdentifier to IPC
- Now rdbi and wdbi work on battery ECU
- Updated timer flags for security SAD nrc in readDataByIdentifier

Updated IPC logic

---

src/ecu_simulation/BatteryModule/src/BatteryModule.cpp
src/ecu_simulation/EngineModule/src/EngineModule.cpp
src/uds/clear_dtc/src/ClearDtc.cpp
src/utils/src/GenerateFrames.cpp

- The first issue was the order in which we opened the file with DTCs.
- The second issue was that the size of a DTC was set larger than it actually was, and it was automatically filled with zeros. This caused incorrect bytes with zeros to be inserted.

DTC size format modified

---

src/rest_api/actions/base_actions.py
src/rest_api/actions/read_info_action.py
src/rest_api/actions/secure_auth.py
src/rest_api/actions/security_decorator.py
src/rest_api/routes/api.py

Decorator that manages separate security checks for the read_info endpoints. It ensures that the session is changed to programming mode and the user is authenticated before accessing the information.

Decorator for handling separate security in Read Info 

---

src/ecu_simulation/BatteryModule/src/BatteryModule.cpp
src/ecu_simulation/EngineModule/src/EngineModule.cpp
src/uds/write_data_by_identifier/utest/WriteDataByIdentifierTest.cpp
src/utils/include/ReceiveFrames.h
src/utils/src/ReceiveFrames.cpp

- Unit tests for the WDBI service fixed (100% coverage)
- Added setter for ecu_state in the utils/ReceiveFrames class to bypass security
- Added absolute paths for ecu*_data.txt and dtcs.txt files to make the tests work

Feature/WDBI UT Fixed

---

src/rest_api/actions/base_actions.py
src/rest_api/actions/read_info_action.py
src/rest_api/actions/security_decorator.py
src/rest_api/actions/write_info_action.py
src/rest_api/app.py
src/rest_api/config.py
src/rest_api/requirements.txt
src/rest_api/routes/api.py

- Adds a decorator to differentiate between manual and automatic flow.
- Integrates Flask-Limiter for rate limiting API requests.
- Bugfix read&write single item for ECU's, double call for passive_reponse

Decorator to Handle Manual/Automatic Flow & Flask-Limiter

---

src/front_end/carsdata/src/components/OTAcomponents/UpgradeButton.tsx

Issue: In the upgrade popup, the buttons for each version were not displayed correctly between units.
Cause: The issue was caused by the mapping over available versions array with a key (the sw_version) that was not unique. This led to a mix-up that displayed more buttons than necessary.
Solution: I also added the position in the array along the version name to make it more unique. Warnings are still displayed but the buttons are well made now. To ensure a complete solution, we will have to take into consideration using the version id along the version name because version names are not always unique.

Solution for Upgrade Button bug

---

src/utils/include/GenerateFrames.h
src/utils/src/GenerateFrames.cpp
src/utils/test/GenerateFramesTest.cpp

-Unit tests for Generate Frames service fixed (98.6% coverage)

UTGenerateFramesFixed

---

src/android_app/CarsData/app/src/main/java/com/poc/p_couds/activities/UDSactivity.kt
src/android_app/CarsData/app/src/main/java/com/poc/p_couds/fragments/Fragment_RequestSendAutomated.java
src/android_app/CarsData/app/src/main/java/com/poc/p_couds/models/DbHelper.java
src/android_app/CarsData/app/src/main/java/com/poc/p_couds/models/IApiService.kt
src/android_app/CarsData/app/src/main/java/com/poc/p_couds/pojo/ChangeStatusSession.java
src/android_app/CarsData/app/src/main/java/com/poc/p_couds/pojo/GetIdentifiers.java
src/android_app/CarsData/app/src/main/java/com/poc/p_couds/pojo/WriteTiming.java
src/android_app/CarsData/app/src/main/java/com/poc/p_couds/pojo/WriteTimingPost.java
src/android_app/CarsData/app/src/main/res/layout/dialog_input_p2time.xml
src/android_app/CarsData/app/src/main/res/layout/fragment_request_send_automated.xml
src/android_app/CarsData/app/src/main/res/values/ids.xml

Integrated Tester Present, Read Access Timing, Write Timing endpoints, Session, Authentication, Read Identifiers in Fragment Semi-Automated
Fixed missing Intent in UDS and duplicate line in DBHelper
Files added:
ChangeStatusSession -pojo
writeTiming -pojo
writeTimingPost -pojo
dialog_input_p2time.xml -layout
Modified:
GetIdinetifiers -pojo
IApiService -models
ReadAccessTiming -pojo
Fragment_RequestSendAutomated -fragments
ApiClient

Integrated endpoints in Send Request Fragment

---

src/utils/src/HandleFrames.cpp

Fixed bug when a request between mcu-ecu was made and a nrc was received. The nrc response was interpreted as another service request and so on..

Bug fix - infinite requests between mcu-ecu

---

.github/workflows/build_checker.yml

Github actions v3 is deprecated, leading to pipeline failures. The aim of this fix is to upgrade to v4 to prevent hiding failures caused by our errors

chore: upgrade actions from v3 to v4
